# shelly 2.5
# 27

substitutions:
  id: light_kitchen_sink
  friendly_name: K端che Sp端lenlicht
  update_throttle: 30s

  name_a: K端che Sp端lenlicht

packages:
  wifi: !include common/wifi_mainfloor.yaml
  device: !include common/device_shelly25.yaml
  template_a: !include common/template_light_binary_a.yaml
