# shelly 2.5
# 17

<<: !include .shelly25.yaml

substitutions:
  name: switch_kitchen_top
  friendly_name: Schalter KÃ¼che oben
  update_throttle: 30s

binary_sensor:
  # device status sensor
  - platform: status
    name: "${name}_status"
  # binary sensor for the button A press
  - platform: gpio
    name: "${name} sensor A"
    pin:
      number: GPIO13
      inverted: false
  # binary sensor for the button B press
  - platform: gpio
    name: "${name} sensor B"
    pin:
      number: GPIO5
      inverted: false
