# gosund sp111 v1.1
# 14

substitutions:
  id: plug_guestroom_videolight_right
  update_throttle: 30s

  name_a: Videolicht rechts
  restore_mode_a: RESTORE_DEFAULT_OFF

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  template: !include common/template_sp111_switch.yaml
