# gosund sp111 v1.1
# 17

substitutions:
  id: plug_bathroom_toothbrush
  update_throttle: 30s

  name_a: Zahnb√ºrste
  restore_mode_a: RESTORE_DEFAULT_OFF

  cf1_pin: GPIO04
  state_led_pin: GPIO02
  status_led_pin: GPIO00
  actor_pin: GPIO15

packages:
  wifi: !include common/wifi_mainfloor.yaml
  template: !include common/template_sp111_switch.yaml
